[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[build.processing]
  skip_processing = false

[context.production.environment]
  SECRETS_SCAN_OMIT_PATHS = "components.js,contact.html,node_modules"